### ISSUE TITLE
Shader error in 'FlatKit/Stylized Surface': 'OUTPUT_SH': Too many arguments for a macro call. 

### ISSUE THREAD

**Issue by Lucasjojo** [Dustyroom/flat-kit-doc#106]
**Describe the bug**
I imported Flat Kit: Toon Shading and Water packeage in my project.But the project reported an error directly.I cant fix this.

**Screenshots**
![1694249161957](https://github.com/Dustyroom/flat-kit-doc/assets/102715771/ff49d63e-e092-455f-a302-2db225ed112b)
![1694249207194](https://github.com/Dustyroom/flat-kit-doc/assets/102715771/e7b149a0-256f-49e8-b812-02a1116020a7)
![1694249239711](https://github.com/Dustyroom/flat-kit-doc/assets/102715771/26758c53-c42c-4be1-9a4d-ad0c923fb6e7)

**Unity details:**
Flat Kit version 3.9.1
Unity 2023.1.11f1
Dev platform: WindowsEditor
Target platform: StandaloneWindows64
URP installed: True, version 15.0.6
Render pipeline: UniversalPipeline
Color space: Gamma
Quality config: [FlatKit] Example URP Asset
Graphics config: [FlatKit] Example URP Asset

**Comment by dustyroom-studio** [comment]
Hi, please try doing the following:
- In Project tab select Flat Kit folder -> Right click -> Reimport
In most cases this fixed importing errors.

If this doesn't help:
- Remove Flat Kit folder completely
- Go to the cache folder (Press Win+R, paste this path and press Enter: `%APPDATA%\Unity\Asset Store-5.x`), delete Dustyroom folder
- Download and import Flat Kit from the Package Manager

Hope this helps.

**Comment by Lucasjojo** [comment]
I have tried the two methods above, but the problem still hasn't been solved.
![_20230909220220](https://github.com/Dustyroom/flat-kit-doc/assets/102715771/26228865-e39e-492b-bf26-0b9c7c9e3961)

**Comment by dustyroom-studio** [comment]
Do you have the project that was made as URP from the start? Or did you upgrade it from Built-in RP?
In any case please make sure you have the properly installed URP packages.

I'd recommend to try creating a temporary fresh URP (!) project and importing Flat Kit into it — It should work out of the box.

**Comment by Lucasjojo** [comment]
I have tried everything you said, but the new URP project still reported that error. Have you tried using the URP rendering pipeline from 2023.1.11f1 to import this resource package?

**Comment by dustyroom-studio** [comment]
You're right, there is an error when using Flat Kit 3.9.1 and URP 15.0.6. We're releasing an update that will address this today.

To add some context, Unity went back and forth with the signature of `OUTPUT_SH` within minor versions of URP. They added another parameter, so we adapted Flat Kit to work with that. Then they probably received a lot of backlash because of broken projects and reverted that change, so we reverted ours back as well. It seems that they settled on two different functions now, which we'll use depending on the Unity version.

Thank you for reporting this!
