### ISSUE TITLE
Terrain Shader Crashes on Import

### ISSUE THREAD

**Issue by JackCollins1991** [Dustyroom/flat-kit-doc#15]
When I import the latest version of FlatKits, the import always causes Unity to freeze while importing the Terrain.shader file. When I stop and restart Unity, the Terrain.Shader asset is corrupted and presents the following error message in editor (screenshot attatched)
Error Message 
"this default asset was generated because the worker process has crashed during last import "

![Terrain Error](https://user-images.githubusercontent.com/55454098/106362361-aa2c4d00-6322-11eb-9168-08560000ea08.JPG)

**Comment by dustyroom-studio** [comment]
First of all, if you are using in 2019.4.x version of Unity, it's better to upgrade your project to 2020.1 or 2020.2 as Unity messed up the Package Manager in 2019, which causes improper importing of the assets from different publishers (including Flat Kit) and reimport Flat Kit ([see the note in the FAQ](https://flatkit.dustyroom.com/#q-i-am-trying-to-import-flat-kit-but-cant-find-urp-package--it-downloads-old-version-of-flat-kit)).
If you can't move to the newer version of Unity, it is still worth to re-import the asset, as we have not received reports about our shaders crashing Unity.
Also, a few questions to help us get the fuller picture:
- what rendering pipeline are you using?
- when exactly does the crash happen? One thing that comes to mind is when you are importing a Built-In RP version Flat Kit into Built-In RP project (as opposed to URP project — see screenshot  of Unity Hub below), it takes from 10 to 20 minutes of time depending on the computer power. If that's the case, please start importing and leave Unity alone for the time it needs to finish compiling the shaders. In URP this issue is not present, everything loads virtually instantly.
![unityhub-builtin-urp-projects](https://user-images.githubusercontent.com/74666746/106362846-bc5fb880-632d-11eb-990d-140202d86d46.png)

Looking forward to your reply.

**Comment by JackCollins1991** [comment]
Hi, I've just managed to fix the issue: I was mistaken - I was not frozen, it was just taking extremely long to import and so it actually took 30 minutes to import just the 7KB terrain.shader file, but it did eventually succeed. Sorry for the mistake. Now I can go ahead with making this game :) Thanks for a good product, it is really helpful!
