### ISSUE TITLE
Pinky came back for all Mats using flatkit after upgrading to 2020.2

### ISSUE THREAD

**Issue by Denchyaknow** [Dustyroom/flat-kit-doc#22]
Everything was fine till I upgraded (yesterday) from 2020.1.12 to 2020.2.6 
All matts become pink just like youd expect when using incompatible shader for the pipeline. I made sure to update all Unity assets like URP. Updated FlatKit last and did a reimport all to no avail. Funny thing is though I still see the outlines on the pinked out meshes. 
**To Reproduce**
1. Upgrade a project using flatkit from .1 to .2

**Unity details:**
 - Flat Kit version: [e.g. 2.1.3]
 - Unity version: [e.g. 2020.2.6f1]
 - Graphics Pipeline: [URP]
 - URP version (if applicable): [latest]
 - Development OS: [Windows]

**Build platform:**
 - Platform: [PC/Android]
 - Test device: [PC]

**Additional context**
This happened upon upgrading a project that default opens up to a FlatKit loaded scene.

**Comment by Denchyaknow** [comment]
Note that one bug I saw included a Function InitializeAll that was failing. Will repost pic of error when I see it again.

**Comment by dustyroom-studio** [comment]
Hi,

I have just tried reproducing your issue, i.e. doing a clean import of Flat Kit into a clean install of Unity 2020.1.12f1 (worked fine). Then I updated Unity to 2020.2.6f1, and it worked without issues.

My initial guess would be that once you updated the Unity version, the Universal RP version (you didn't mention yours) got updated as well. Something might have broken during the materials upgrade for the newer version of Universal RP. Unity versions prior to 2020.2.1f1 are problematic in terms of managing packages versions, which is a known bug, Thus, it is probably why updating to the 'fixed' version of Unity brought up unexpected issues like yours. Re-importing Flat Kit for the updated Universal RP may do the trick.

Could you please try doing the following:
- Open the project and remove Flat Kit folder from Project tab;
- Close Unity;
- Go to C:\Users\accountName\AppData\Roaming\Unity\Asset Store-5.x and remove cache;
- Open the project again, navigate to Window -> Package Manager -> My Assets -> Flat Kit (the available version should be 2.1.4 at this current moment)
- Press Download, then press Import and then unpack Flat Kit as described in the [guide here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)

If after going through these steps the issue is still there, please let me know.

**Comment by Denchyaknow** [comment]
Thank you for the quick reply!
I literally woke up, followed your instructions (Even though I tried similar steps) and it worked!
Your right I did forget to check for URP updates before I updated Unity to .2 silly me!
I was a little worried thinking the Material refs for all my prefabs would break but NON, all is good. I got a few ambiguous errors from the Editor/Readme.cs script (prolly namespace issues) but once I deleted it everything was back to norm. Not a big deal just thought u should know, didnt think it was worth a whole bug report.

Keep up the good work m8
