### ISSUE TITLE
Built-In shader package only has URP shaders.

### ISSUE THREAD

**Issue by guillermo-borges** [Dustyroom/flat-kit-doc#25]
**Describe the bug**
[Render Pipeline] Built-In.unitypackage doesn't actually have the built in shaders. Only URP ones. I'm getting this error:

Shader error in 'FlatKit/Stylized Surface': Couldn't open include file 'LibraryUrp/StylizedInput.hlsl'. at line 243

This shouldn't happen since I clearly imported the built-in package.

**To Reproduce**
1. Download the latest version.
2. Import
3. Install the built-in package.
4. Browse to Stylized Surface shader, see import errors. It expects URP dependencies that aren't there.

**Expected behavior**
Built-In should come with built-in shaders.

**Unity details:**
 - Flat Kit version: [e.g. 2.1.4]
 - Unity version: [e.g. 2021.11b]
 - Graphics Pipeline: [Bult-in]
 - Development OS: [e.g. Windows]

**Comment by dustyroom-studio** [comment]
Hi,
Thank you for reporting this and for sharing the details. We'll look into it shortly and get back to you.
Thank you for your patience.

**Comment by dustyroom-studio** [comment]
This should be fixed in Flat Kit 2.1.5, which is currently in review by Unity.

**Comment by guillermo-borges** [comment]
Thank you. I am temporarily working with URP and the shader is great. I'll update my review when the new version is out :)

**Comment by dustyroom-studio** [comment]
Hi Guillermo,

The update is live, you can try updating now.
Since you are using a Built-In RP, please note that in Built-In RP Flat Kit can take up to 20 min to get imported (in URP it imports immediately).

Also, please, use a stable version of Unity instead of beta — with 'f' in its title, not 'b' (2020.2.6f1, not 2021.11b1). Chances are it won't work in a beta version of Unity as before updating we need to include the working versions of Unity.

If you won't be able to use the 'Update' button in Package Manager to update Flat Kit to 2.1.5, please clear the cache
and restart Unity. You'll see 'Download' button as it is on the screenshot:  
![Screen Shot 2021-03-15 at 4 11 52 PM](https://user-images.githubusercontent.com/74666746/111166991-5790b280-85a9-11eb-98c5-465063b83dfe.png)

Let me know if you'll have any questions.
