### ISSUE TITLE
Shadows/Depth not showing in build

### ISSUE THREAD

**Issue by Plnda** [Dustyroom/flat-kit-doc#34]
**Describe the bug**

Currently, im having an issue, that the shadows won't render in a build version of the game, but in the editor it will show up nicely, it seems like depth effects also do not work properly in the buildt version of the game. I do have other shadows showing, also i have everything cranked to max as graphics settings.

**Expected behavior**
I would expect the same behaviour in editor as in the final build

**Screenshots**
https://www.dropbox.com/s/kr29sf22nph2umg/editor.png?dl=0
https://www.dropbox.com/s/7076a6nurzve3yp/build.png?dl=0

**Unity details:**
 - Flat Kit version: 2.1.1
 - Unity version: 2020.2.5f1
 - Graphics Pipeline: URP
 - URP version (if applicable): 10.3.1
 - Development OS: Windows

**Build platform:**
 - Platform: Windows
 - Test device: Windows

**Comment by vdzitsiuk** [comment]
Hi,

Thank you for using Flat Kit and for all the included details.

I'm afraid, from the screenshots it is not crystal clear what exactly shadows do you mean. On both of the screenshots I can see the cast shadows from the trees. The cel shadows seem to be displayed as well. Could you please emphasize the problematic spots?

Some of the depth issues were fixed in the newer version of Flat Kit, 2.1.6. Could you please try updating to this version?

Prior to updating Flat Kit, please, consider updating Unity to at least 2020.3.1.f1 LTS (if you are planning to continue using 2020's range of Unity)

Also, could you please check your settings in the Edit - Project Settings -> Quality tab? Is it set as described [in the manual here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)?

Let me know if the issue is still there after you try updating Flat Kit and Unity.

**Comment by dustyroom-studio** [comment]
Hi,

Thank you for using Flat Kit and for all the included details.

I'm afraid, from the screenshots it is not crystal clear what exactly shadows do you mean. On both of the screenshots I can see the cast shadows from the trees. The cel shadows seem to be displayed as well. Could you please emphasize the problematic spots?

Some of the depth issues were fixed in the newer version of Flat Kit, 2.1.6. Could you please try updating to this version?

Prior to updating Flat Kit, please, consider updating Unity to at least 2020.3.1.f1 LTS (if you are planning to continue using 2020's range of Unity)

Also, could you please check your settings in the Edit - Project Settings -> Quality tab? Is it set as described [in the manual here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)?

Let me know if the issue is still there after you try updating Flat Kit and Unity.

**Comment by Plnda** [comment]
I will update later today, i was talking about the player not showing any depth effects, and also not casting any shadows as you can see on the editor screenshot where it does, (side of the pond)

**Comment by Plnda** [comment]
@dustyroom-studio You can close this issue, updating to the latest version of flatkit has solved my issue's <3
