### ISSUE TITLE
Shader error in 'FlatKit/Stylized Surface': undeclared identifier 'GetNormalizedScreenSpaceUV' 

### ISSUE THREAD

**Issue by leovargasm** [Dustyroom/flat-kit-doc#38]
Shader error in 'FlatKit/Stylized Surface': undeclared identifier 'GetNormalizedScreenSpaceUV' 

**To Reproduce**
Install the Flatkit, drag some demo materials on my project
made my mesh invisible.
i made a new project and flat kit works, but in my current return that error.

**Expected behavior**
visible material 

**Screenshots**

**Unity details:**
Flat Kit: 2.1.5, URP: 8.3.1, Unity: 2020.2.0b2

**Build platform:**
Windows

**Additional context**
maybe i ruined my project configuration without knowing

**Comment by dustyroom-studio** [comment]
Hi, thank you for adding these details. 

This might be because you use too old version of URP and Unity. The problem I'm talking about is [a well known bug of Unity](https://issuetracker.unity3d.com/issues/package-manager-doesnt-show-available-updates), which they fixed in later versions. Also, here's [a note about this issue in the manual](https://flatkit.dustyroom.com/#q-after-importingupdating-flat-kit-the-shaders-failed-to-compile-x-shader-is-missing-from-the-list-why).

Moreover, you are using a beta version of Unity. Flat Kit _may_ support betas but is not tested with them. Please, use release versions of Unity (they have 'f' in the version title instead of 'b').

So, here's what to do:
- Install to the latest version of Unity within a major version (you work in 2020's, so the latest version to date is 2020.3.4f1). This will update Universal RP version as well.
- Open current or create a new Universal RP project in Unity Hub with newly installed Unity
- Delete Flat Kit 2.1.5
- Open Window - Package Manager - My Assets (a drop-down menu) - Flat Kit
- Press Update (a small arrow icon next to Flat Kit title). Currently the latest version of Flat Kit is 2.1.7
- Follow the instructions in [this video / text guide](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)

Please, note, that if you don't have Download button in Package Manager, you'll need to clean the cache:
_Mac OS: (press Shift+Cmd+G in any Finder Window and paste this path)_ 
~/Library/Unity/Asset Store-5.x

_Windows: (replace accountName with your actual account name)_ 
C:\Users\accountName\AppData\Roaming\Unity\Asset Store-5.x)

Please let me know if the issue persists.

**Comment by dustyroom-studio** [comment]
It is also possible that `GetNormalizedScreenSpaceUV` was added to the URP after your current version.
Is there any reason you are not updating URP in the package manager? Also updating to a stable version of Unity might help.

**Comment by leovargasm** [comment]
this works!!! thanks, the only bad thing was NoiseMotion script give me a lot of errors, i dont know for what is this script, i commented evertthing and works smoothly, Thanks a lot for the quick response!! love the shaders :D
