### ISSUE TITLE
Skybox and Lightplane shaders don't work in VR 

### ISSUE THREAD

**Issue by kevenson** [Dustyroom/flat-kit-doc#43]
**Describe the bug**
Neither the skybox nor the lightplane shaders (built-in, not URP) work in Unity 2020.3.1f1 targeting the Quest 2 w/ single pass/multiview rendering. Using the Oculus Integration package. 

**To Reproduce**
1. Setup Unity using the built-in rendering pipeline for the Quest 2 using single pass/multiview rendering and OpenGLES3 API.
2. Open Valley demo scene with fog, and replace Camera 1 with OVRCameraRig
3. Copy Fog Image Effect to CenterEyeCamera
4. Try to run the scene
5. Try again without fog (known to have issues w/ SP rendering)

**Expected behavior**
The lightplanes show up as bright pink and the skybox is crazy - you can't see in the screenshots but when you look around, the outline from the trees gets repeated over and over across the entire skybox

**Screenshots**
See attached
![ToonShaderExpected](https://user-images.githubusercontent.com/12128350/117161840-3fab0300-ad90-11eb-8a84-e366530ccce2.PNG)
![ToonShaderActual](https://user-images.githubusercontent.com/12128350/117161843-40439980-ad90-11eb-8826-8501dfd6a70b.PNG)
![ToonShaderActualWithoutFog](https://user-images.githubusercontent.com/12128350/117161848-40dc3000-ad90-11eb-82ef-c7ce985779f3.PNG)

**Unity details:**
 - Flat Kit version: [e.g. 2.1.5]
 - Unity version: [e.g. 2020.3.1f1]
 - Graphics Pipeline: [Bult-in]
 - Development OS: [Windows]

**Build platform:**
 - Platform: [Quest 2 / Android]
 - Test device: [Rift S]

**Additional context**

Thanks!

**Comment by dustyroom-studio** [comment]
Hi,

Could you please try doing the following:
- In URP — check if you have **[Flat Kit] Example Settings URP** set in **Quality** Settings panel for **all Quality levels**, also verify if this file is set in **Graphics** panel as well? 

![manual_import_instructions_7](https://user-images.githubusercontent.com/74666746/117173254-4445da80-add5-11eb-9993-937ab76a82cf.png)

![manual_import_instructions_6](https://user-images.githubusercontent.com/74666746/117173279-490a8e80-add5-11eb-9d2c-3ed15d74576d.png)

- Could you please update Flat Kit to the latest version (currently it's 2.1.8)? 

![package-manager-update](https://user-images.githubusercontent.com/74666746/117175445-8839df00-add7-11eb-9a55-c5047d273a95.png)

To check whether you have the latest version, please select the Readme file (Project panel -> Assets -> Flat Kit -> Readme).


![flat-kit-readme-screenshot_1](https://user-images.githubusercontent.com/74666746/117175534-a1db2680-add7-11eb-83b5-1794ab361dac.png)


- For Built-In RP, can you please try re-importing Flat Kit? Please, note, [it can take a while](https://flatkit.dustyroom.com#q-it-takes-very-long-to-import-flat-kit-into-unity-in-built-in-rp).

- Let us know, do the Skybox and LightPlane work in Game mode in the Editor with standard camera but don't work with Oculus?

Please, note that because Built-In RP is being deprecated by Unity, we continue to support it with Flat Kit, but we don't add new features to Built-In RP. Is it possible for your project to be developed in Universal RP? Otherwise, we'll offer you a refund.

**Comment by kevenson** [comment]
Thanks for getting back to me so quickly. I've tried updating my project to URP, updating FlatKit to 2.1.8, and making sure I have [Flat Kit] Example Settings URP set in Quality Settings panel for all Quality levels, as well as in Graphics panel. I also updated Unity to 2020.3.7f1 but I'm still having the same issues for URP using Single Pass Instanced / Multiview rendering.

For URP: 
- skybox works in Game mode in the Editor, but not in the HMD (the bizarre image defects are only to the right eye of my Oculus HMD)
- lightplanes do not work in Game mode in the Editor or the HMD (show up as bright pink)

For the Built-In pipeline, I've also updated FlatKit to 2.1.8, reimported it, updated Unity to 2020.3.7f1 and I still have the exact same issues.
- skybox works in Game mode in the Editor, but not in the HMD (the bizarre image defects are only to the right eye of my Oculus HMD)
- lightplanes do not work in Game mode in the Editor or the HMD (show up as bright pink)

If I try replacing the OVRCameraRig with a standard camera, the skybox works in the Editor (this is also true for the OVRCameraRig), but the LightPlanes don't seem to be rendered at all. 
 
These features do work (and look beautiful!) with Multipass rendering, it seems to be a Single Pass Instanced / Multiview Rendering issue.

**Comment by dustyroom-studio** [comment]
Hi,

To make sure I'm aware of your setup and what you have tried:
- You tried Flat Kit **v2.1.8** in Universal RP, **not only in Built-In RP**. LightPlane, Skybox, Fog, Outline had been successfully tested for compatibility with Oculus in 2.1.8 in Universal RP. That's why asking to verify it.
- You've got Universal RP version 10.4.0 installed in your project.

![UniversalRP-package-v10 4 0](https://user-images.githubusercontent.com/74666746/117476574-b3523900-af65-11eb-9a93-a08ed84c1438.png)

If all above is 'yes', could you please send us a set-up log to info@dustyroom.com? You can generate it here:

![flat-kit-readme-screenshot](https://user-images.githubusercontent.com/74666746/117475473-c31d4d80-af64-11eb-9124-c8fb7e97efa2.png)

![flat-kit-readme-copy-debug-info-2](https://user-images.githubusercontent.com/74666746/117476855-fb715b80-af65-11eb-84e6-d1df24a22d82.png)

**Comment by kevenson** [comment]
Thanks, Volodymyr. Will these FlatKit components (lightplanes & fog) ever be supported in the Built-in RP for Single-Pass/Multiview render modes?

**Comment by mutp** [comment]
I'm facing the same issue but I'm targeting Single pass/Multiview for URP. Looking forward to the fix for it.

**Comment by dustyroom-studio** [comment]
Hi @mutp, 

We are aware of this problem and keep trying to get it working. In URP 11 Unity completely changed the stereo rendering (XR) and there is no documentation from Unity. It is a new version (of URP),and  for now it is complicated, so we need some time.
Thank you for your patience.

**Comment by dustyroom-studio** [comment]
Hi! Light Plane and Skybox, as well as Single Pass Stereo should be fixed in Flat Kit 2.9.0, please check it out.
