### ISSUE TITLE
AlphaClipping does not work on outlines.

### ISSUE THREAD

**Issue by kisabon** [Dustyroom/flat-kit-doc#44]
**Describe the bug**
AlphaClip is used for detailed character decoration.
It seems that the alpha clip is not applied to the outline, which results in a square edge.
I want to apply an outline to a transparent edge, is there a workaround

**Screenshots**
[https://gyazo.com/47342d76e7f2dfd1a5070a5e689f7340](url)

**Unity details:**
 - Flat Kit version: [e.g. 2.1.3]
 - Unity version: [e.g. 2020.2.3f1]
 - Graphics Pipeline: [Bult-in or URP]
 - Development OS: [e.g. Windows]

**Build platform:**
 - Platform: [e.g. Unity Editor]

**Comment by dustyroom-studio** [comment]
Hi,

Unfortunately, I can't find where the issue is on the screenshot you provided. Could you please either describe what's on the left side of it and what's on the right? I can see the rectangle on the left and cutout on the right, but it has outlines.

What happens when you move the clip slider all the way left the all the way right?

Please, let me know which of two outlines you are using — Stylized Surface with Outline or Outline global image effect?

Finally, could you please let me know your setup details like Unity and Flat Kit versions, is it Universal or Built-In RP?

Thank you

**Comment by kisabon** [comment]
Hi,

[Stylized Surface] without Outline will be alpha-clipped.
[Stylized Surface with Outline] does alpha clipping, but it is not valid for outlines.
I have captured the operation in a video. Thank you for your cooperation.
[video](https://drive.google.com/file/d/1BZbF8dx43NQZxjagYvbKSBKhJf4b5wzO/view?usp=sharing)

Unity details:

Flat Kit version: [2.1.8]
Unity version: [2020.3.7f1]
Graphics Pipeline: [URP]
Development OS: [Windows]
Build platform:

Platform: [Unity Editor(Universal Render Pipeline Template)]

**Comment by dustyroom-studio** [comment]
Thank you for the video, now the request is clear. Alpha clip of the outline pass is not part of Flat Kit functionality at the moment. We are hesitant to add any per-pixel functionality in the outline pass for performance reasons.

However, the Material UI needs to at least warn the users that these settings are incompatible.

Can the same effect be achieved in your project by using the [Outline Image Effect](https://flatkit.dustyroom.com/#42-outline-image-effect)?
