### ISSUE TITLE
Issue with Orthographic camera in water shader 

### ISSUE THREAD

**Issue by AnkitNarsingani** [Dustyroom/flat-kit-doc#48]
When we place the water shader on a plane and set the camera mode to orthographic, the foam that forms on the edges seems to be acting weird. On some devices the edges appear jaggy and on other devices the water is completely white.  It looks fine in the editor (in orthographic mode) but the issue arises on build. It works as expected on the perspective camera (both editor and build).

**Screenshots**
![White Water](https://user-images.githubusercontent.com/43947543/119961967-38100000-bfc4-11eb-8e08-cefa979a380e.jpg)
![Jaggy Edges](https://user-images.githubusercontent.com/43947543/119961982-3b0af080-bfc4-11eb-9859-a2125bd5f1a7.jpg)

 - Flat Kit version: [2.1.1]
 - Unity version: [e.g. 2019.4.17f1]
 - Graphics Pipeline: [URP]
 - URP version (if applicable): [7.3.1]
 - Development OS: [Windows]

 - Platform: [Android]
 - Test device: [Realme 3 Pro, Honor 7X]

**Comment by dustyroom-studio** [comment]
Hi,

Could you please:
- Update Unity to the latest 2019 version, or to 2020.3.x.
- Check the real version of Flat Kit, Unity and Universal RP versions. I mean 'real' because your Unity version is likely to be having a Package Manager bug, which gives wrong info about the packages. (More info here:
https://flatkit.dustyroom.com/#q-after-importingupdating-flat-kit-the-shaders-failed-to-compile-x-shader-is-missing-from-the-list-why).
The real versions numbers can be found using Flat Kit's **Readme** tool - here:
https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit

If you don't see a **Readme** tool, you have an old version of Flat Kit. In this case, could you please update it?

**Comment by AnkitNarsingani** [comment]
Upgrading to 2020 and reimporting the asset solved it. Thank you, I'll close the issue now.
