### ISSUE TITLE
Outline Render Feature causes masked UI elements to no longer be masked

### ISSUE THREAD

**Issue by Geko-X** [Dustyroom/flat-kit-doc#55]
**Describe the bug**
Enabling the outline render feature causes masked UI elements to become unmasked. This includes both images and text.

**To Reproduce**
1. Create a masked image or text UI element
2. Set up the outline render feature as described in the [docs](https://flatkit.dustyroom.com/#42-outline-image-effect).

**Expected behavior**
The outline render feature does not unmask masked UI elements.

**Screenshots**

Outline disabled, UI is masked correctly
![2021-07-14-11-16-04](https://user-images.githubusercontent.com/11388300/125546195-23e33e59-d942-4c5f-849c-cd204f2502a3.png)

Outline enabled, UI is no longer masked. See around the "FIGHT" button and the bottom of the changelog
![2021-07-14-11-15-39](https://user-images.githubusercontent.com/11388300/125546245-9007fce9-7e38-484d-83cb-f4384060997b.png)

The forward render asset
![image](https://user-images.githubusercontent.com/11388300/125546313-b501e192-a1dc-4021-bec2-f27af9588608.png)

The outline settings
![image](https://user-images.githubusercontent.com/11388300/125546359-802ab4e8-a215-4f2b-9e95-54b0c3aa92ec.png)

**Unity details:**
 - Flat Kit version: 2.3
 - Unity version: 2020.3.12f1
 - Graphics Pipeline: URP
 - URP version (if applicable): 10.5.0
 - Development OS: Windows

**Build platform:**
 - Platform: Windows
 - Test device: Windows PC (GTX 1080)

**Additional context**
This only occurred after I had upgraded from FlatKit 2.1.7

**Comment by dustyroom-studio** [comment]
Hi,

Flat Kit's outlines are not designed for UI. In two words, it is not easy to place an outline on 2d canvas UI elements.

If the issue was not in adding an outline to UI, but rather in the fact that adding an outline unmasked the UI element, I've tried to replicate this issue. I'm not sure how you achieved your mask effect, but in my case the mask remained working with an Outline renderer feature added. I placed a 'Button' object of the Canvas into a 'Mask' object and added a 'Mask' component on the latter.

![outline_with_masked_ui_on_scene_1](https://user-images.githubusercontent.com/74666746/125570446-5f9f732b-1eb6-4582-b7b1-64d9a4342834.png)

One of the reasons of such a behavior could be the fact that you use an opaque material for your UI elements. Could you please try making a simple test scene with a very basic UI elements — a button and a mask, and looking whether it works. After that, keep adding or changing features until the issue appears.

Let me know if you have any questions.

**Comment by Geko-X** [comment]
Hi, thanks for looking into this.

I've taken a more in depth look at my project, and have some additional details that may help.

- The MainCamera does not render the UI layer, and has its culling mask to all layers _except_ for UI.
- A second camera, UICamera, renders only the UI. It is set as an overlay camera and included in the MainCamera's camera stack. Its culling flags are set to _only_ the UI layer. This is done to exclude the UI from other post processing.
- All UI is in the UI layer. 
- I can validate that there are no opaque materials in the UI. Setting the transparent layer filter to nothing in the forward renderer asset (ie: setting it to only render opaques) results in nothing being rendered.
- The button is set up as follows. The mask sits under the Button component and above the images in the hierarchy.
![image](https://user-images.githubusercontent.com/11388300/125579562-c40c9bd5-2b38-4082-9788-eff7776d75dc.png)

- The scroll view is a standard scroll view setup, created by right-clicking -> UI -> scroll view. Text is added with a TextMeshPro component, and resized using a content size fitter
![image](https://user-images.githubusercontent.com/11388300/125579929-bade9219-8791-4f5c-a4d6-4b7308f01d41.png)

- Changing the render event to "After Rendering Rendering Pre Pass" or before yields the expected behaviour, and anything after "Before Rendering Transparents" yields this:
![image](https://user-images.githubusercontent.com/11388300/125581107-0f525640-c64d-482f-974f-3d5a1ae4f69a.png)

- Any other render features work as expected, however FlatkitFog unmasks UI elements if its render event is set to anything between "After Rendering Rendering Pre Pass" and "After Rendering Transparents" exclusive.

**Comment by dustyroom-studio** [comment]
Since you use two cameras for two independent effects — have you tried setting both of the cameras to separate Forward Renderers?

![cameras-1](https://user-images.githubusercontent.com/74666746/125592108-b8b6eb7e-22ba-455b-8a5f-d7b4ebc6b81e.png)

After applying the details you mentioned previously, I still cannot replicate your issue. Here's what my scene looks like:
![scene-with-ui](https://user-images.githubusercontent.com/74666746/125592396-492b011b-9672-49b5-ba0b-21adc96a9f82.png)

I guess, there are too many things we set up differently, and I still can't see your whole preferences and settings.

Have you tried, for the test purposes, stripping down the scene or making the simplest test scene from scratch? This way it would be easier to find the cause of an issue. If this scene doesn't work, could you please pack it, and send it to info@dustyroom.com? We'll have a look at it as soon as we can.

**Comment by Geko-X** [comment]
Hi,

I've recreated the issue in a fresh project and have sent it over.
