### ISSUE TITLE
Turning on "Override light direction" via code doesn't seem to work.

### ISSUE THREAD

**Issue by Jointy87** [Dustyroom/flat-kit-doc#65]
Turning on 'override light direction' and setting pitch/yaw values during runtime via code doesn't seem to work correctly.

material.EnableKeyword("DR_ENABLE_LIGHTMAP_DIR");
material.SetFloat("_OverrideLightmapDir", 1);
material.SetFloat("_LightmapDirectionPitch", pitchValue);
material.SetFloat("_LightmapDirectionYaw", yawValue);

So during runtime there's no change to the material. However, if I select the mesh and fold open the material instance, all of a sudden it works. Not sure if this is a bug or I just can't find the correct keyword to enable, but any help would be much appreciated. 

**Unity details:**
 - Flat Kit version: Unsure, I can't find it in my 'in project' section of Unity Package Manager.
 - Unity version: 2020.3.25f1
 - Graphics Pipeline: URP
 - URP version: [e.g. 10.7.0]
 - Development OS: Windows

**Build platform:**
 - Platform: Unity Editor

**Additional context**

**Comment by dustyroom-studio** [comment]
Hi,
To find out the version of Flat Kit, you'll need to go into Package Manager, and look at the 'Packages' menu -> 'My Assets'. You should see Flat Kit there.
Also, you can locate the [Readme] file, by default it is in the Assets/Flat Kit folder and see the Flat Kit version there

This info, with a video guide as well as the screenshots, is in the Flat Kit documentation [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit) — please, look at the step-by-step installation guide or just watch the video guide.

Could you please locate the [Readme] file, press the 'Copy debug info' button and paste it here?

**Comment by dustyroom-studio** [comment]
Hi @Jointy87 ,

What you are seeing is because some of the material properties are set by our custom Material Inspector (the class `StylizedSurfaceEditor`). Most properties should work fine when setting directly (like a color or a texture), but some others (like toggling a feature) are not possible at runtime because they require re-compiling the shader. We use compile-time shader features for performance reasons.

I suggest that you enable the keyword via the material inspector (instead of doing `material.EnableKeyword("DR_ENABLE_LIGHTMAP_DIR");`). The light angle then can be controlled via code as you are doing above. If you absolutely need a runtime toggle of the whole feature, you can use two separate materials with both states of the toggle, and switch between the materials via code.

**Comment by Jointy87** [comment]
Hey,

Thanks again for the quick reply and for the help. I'll have to tackle it slightly different than I initially intended then. Cheers!
