### ISSUE TITLE
Shader Error (2021.3 LTS, URP 12.1.6)

### ISSUE THREAD

**Issue by ary1111** [Dustyroom/flat-kit-doc#76]
**Describe the bug**
We are in the process of upgrading to 2021.3 LTS and URP 12.1.6. When we upgraded our project, none of the Stylized Surface materials were rendering properly and we received an error:

`Shader error in 'FlatKit/Stylized Surface': 'InitializeInputData': output parameter 'inputData' not completely initialized at Assets/FlatKit/Shaders/StylizedSurface/LibraryUrp/LitForwardPass_DR.hlsl(55) (on d3d11)`

Also, Flatkit Stylized surface is under "Failed to compile" in the shader dropdown

**To Reproduce**
1. Update project to 2021.3.1
2. Apply FlatKit/Stylized Surface to material
3. See error

**Expected behavior**
Materials are not rendering properly, as they're coming up as pink.

**Screenshots**
![image](https://user-images.githubusercontent.com/18470260/165552562-ffa49230-f483-4bb8-944b-b498c451f88b.png)

**Unity details:**
 - Flat Kit version: 2.9.8
 - Unity version: 2021.3.1 LTS
 - Graphics Pipeline: URP
 - URP version (if applicable): 12.1.6
 - Development OS: Windows
 
 edit: modified steps to reproduce

**Comment by dustyroom-studio** [comment]
Hi!
We heard about this error from another Flat Kit user, so we can help. This error is strange, because it seems to only happen when a project is upgraded to a newer Unity version and Unity's shader updater messes up our shaders. We haven't been able to reproduce this error, but either of these steps should solve it:

1. Remove Flat Kit folder from your project, then re-download and re-import it with the Package Manager.
OR
3. Open `FlatKit\Shaders\StylizedSurface\LibraryUrp\LitForwardPass_DR.hlsl` and add the following line at the beginning of the function `InitializeInputData` at line 55. This line should be already there, but I think that's what the Unity updater is deleting:
```
inputData = (InputData)0;
```

**Comment by ary1111** [comment]
I modified the line as you suggested and that fixed all the materials! Thank you for your quick response and continued support.

**Comment by chyizhiyu** [comment]
> Hi! We heard about this error from another Flat Kit user, so we can help. This error is strange, because it seems to only happen when a project is upgraded to a newer Unity version and Unity's shader updater messes up our shaders. We haven't been able to reproduce this error, but either of these steps should solve it:
> 
> 1. Remove Flat Kit folder from your project, then re-download and re-import it with the Package Manager.
>    OR
> 2. Open `FlatKit\Shaders\StylizedSurface\LibraryUrp\LitForwardPass_DR.hlsl` and add the following line at the beginning of the function `InitializeInputData` at line 55. This line should be already there, but I think that's what the Unity updater is deleting:
> 
> ```
> inputData = (InputData)0;
> ```
> 
> In context:
> 
> ```
> void InitializeInputData(Varyings input, half3 normalTS, out InputData inputData)
> {
>     inputData = (InputData)0;
>     inputData.positionWS = input.posWS;
> ```

I modified the line as you suggested and that fixed all the materials! Thank you very much!

**Comment by JahanzebAD** [comment]
and if yet your problem will not resolve then comment this line in the same shader script
![Screenshot_1](https://github.com/user-attachments/assets/8ef7072f-4a53-4f14-9ee5-03c9c9178117)
