### ISSUE TITLE
[URP] Bug: [Worker0] Trying to get RenderBuffer with invalid antiAliasing (must be at least 1)

### ISSUE THREAD

**Issue by doogieWot** [Dustyroom/flat-kit-doc#79]
**Describe the bug**
Error in Console when you have the inspector window open, and a prefab or material selected when pressing play, or when selecting a prefab or material immediately after exiting play mode.

Error is:
[Worker0] Trying to get RenderBuffer with invalid antiAliasing (must be at least 1)
And sometimes, though not always, comes after the error:
[Worker0] Attempting to get Camera relative temporary RenderTexture (width || height <= 0) via a CommandBuffer  in a Sriptable Render Pipeline.

**To Reproduce**
1. Make a new project
2. Import Flat kit and run the "Configure project for URP" function of the readme.
3. Create a new material.
4. With the material selected press play.
5. If it doesn't trigger there (it should first time but not after that) then exit playmode and create a new material and this will trigger it.
It will only happen once after exiting play mode, then never again until you start and exit play mode again.

**Expected behavior**
No error.

**Unity details:**
 - Flat Kit version: 2.9.8
 - Unity version: 2021.3.2f1
 - Graphics Pipeline: URP
 - URP version (if applicable): 12.1.6
 - Development OS:  Windows

**Build platform:**
 - Platform: Windows

**Additional context**
It appears to only happen when the project window is creating the thumbnail for the material or prefab or if the inspector preview panel is open . If I close the inspector window Unity doesn't draw thumbnails and I can't get the error to trigger at all. And whenever it happens there's a lag time to the Project window drawing the thumbnail preview of the object.

**Comment by dustyroom-studio** [comment]
Thank you for reporting this. I'm also getting this error from time to time, but unfortunately hasn't been able to fix it so far.
This seems to be a Unity bug that has been reported to them several times and marked fixed by Unity ([issue](https://issuetracker.unity3d.com/issues/antialiasing-invalid-antialiasing-value-must-be-at-least-1-error-on-antialiasing-disabled), [forum thread](https://forum.unity.com/threads/worker0-trying-to-get-renderbuffer-with-invalid-antialiasing-must-be-at-least-1.1202689/).

There's another bug that usually comes along with it `Attempting to get Camera relative temporary RenderTexture (width || height <= 0) via a CommandBuffer in a Scriptable Render Pipeline.` ([issue 1](https://issuetracker.unity3d.com/issues/urp-attempting-to-get-camera-relative-temporary-rendertexture-is-thrown-when-tweening-the-viewport-rect-values-of-a-camera), [issue 2](https://issuetracker.unity3d.com/issues/urp-attempting-to-get-camera-relative-temporary-rendertexture-is-thrown-when-no-renderer-features-exist).

From the forums, some people managed to fix this by deleting the Script Assemblies folder, but the errors re-appear after a while. We're keeping an eye for a proper solution.

However, I'm sure that the error is harmless and only appears in the Editor, so can be safely ignored.

**Comment by doogieWot** [comment]
Deleting the script assemblies folder seems to have helped. It still pops up occasionally but at least it's not complete spam like it was. Oddly enough when I deleted the entire Library folder before it seemed to have no effect at all! Thanks for the help.
