### ISSUE TITLE
Point Lights and Spotlights have a dark spot in the "center" of the cast light on Windows OS with AMD GPU (URP)

### ISSUE THREAD

**Issue by KjartanKennedy** [Dustyroom/flat-kit-doc#81]
**Describe the bug**
Point lights and spotlights have a dark spot in the "center" of the light cast on geometry using the flat kit on one team member's machine (Windows, AMD GPU), but other team members' lighting works as expected (no one else has an AMD GPU however).

**To Reproduce**
We've been unable to reproduce the issue on any other computer and unable to get rid of the issue on the offending machine, but here's what we can provide:
1. Set up a Unity project with URP and Flat Kit (versions detailed below)
2. Create a flat plane with a Flat Kit shader/material applied
3. Replace the directional light with a point light or spotlight pointed at the plane
4. Observe the dark spot in the "center" of where the light shines on the plane

**Expected behavior**
The "center" of the light should be lit normally as the brightest part.

**Screenshots**
Incorrect lighting on Windows with AMD GPU
![image](https://user-images.githubusercontent.com/51497099/171408335-2763a424-b90a-4dbb-a3e1-444e485946a9.png)

Correct lighting on Macbook Pro with Apple Silicon
<img width="1584" alt="CleanShot 2022-06-01 at 07 48 24@2x" src="https://user-images.githubusercontent.com/51497099/171408100-bab82bbf-2fab-426f-972e-2bc8be34e286.png">

**Unity details:**
Flat Kit version 2.9.8
Unity 2021.2.3f1
Dev platform: OSXEditor
Target platform: StandaloneWindows64
URP installed: True, version 12.1.1
Render pipeline: UniversalPipeline
Color space: Linear

**Additional context**
As mentioned, this is only happening on one team member's machine using Windows and an AMD GPU, with graphics drivers being fully up to date. Switching to a non-flatkit material removes the problem. We are using real-time lighting.

**Comment by dustyroom-studio** [comment]
Hi,

Could you please check if you use any 3rd party assets in your project that interfere with Unity's URP and/or lighting? From the screenshots of the Console errors I can tell that there may be some of the tools in the project that could cause this issue. To learn if they do cause an issue, could you please, for the testing purpose, create a fresh URP project and import nothing but Flat Kit, [complete its setup](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit) it's setup and try reproducing the problem?

Also, what happens if you temporarily turn off the Outline?

**Comment by KjartanKennedy** [comment]
We've tried disabling all of the render features and deleting all of the other packages we believe could be causing the issue with no luck, however starting a fresh project with _only_ URP and FlatKit did not cause the issue. We're a bit perplexed, but we'll spend a bit more time copying over settings and such to the fresh project to try to discover what may be causing it.
