### ISSUE TITLE
URP version not rendering correctly.

### ISSUE THREAD

**Issue by Gohloum** [Dustyroom/flat-kit-doc#83]
Hello,

I was able to get the built in render version to work just fine.  Now experimenting with the URP.

I installed the URP package from Unity first this time and then installed the FlatKit package.

I have no errors, but the rendering is definitely not correct.  For most of the example scenes, I am seeing just colored background and I can't see the models rendering correctly.  Best way to describe this is to show you screen shots of a few of the FruitVase scenes.  You can also see my debug info on the right.  I have also included the project settings to show I have the example renderer set as expected.  I also tried using clearing he package manager cache and setting the project config to URP based on your [ReadMe] asset.

![Screenshot 2022-07-05 19 43 04](https://user-images.githubusercontent.com/6265945/177435312-ae540e03-f725-4326-9b2e-e5b47907ea1f.png)
![Screenshot 2022-07-05 19 43 15](https://user-images.githubusercontent.com/6265945/177435313-3dd27bee-548d-45ae-9e8b-b683bfece315.png)
![Screenshot 2022-07-05 19 43 32](https://user-images.githubusercontent.com/6265945/177435316-3e7c7ff2-a1a6-4f1f-9727-0866e5d938c3.png)
![Screenshot 2022-07-05 19 43 36](https://user-images.githubusercontent.com/6265945/177435319-8fd9d691-a519-413c-9ebb-093596375898.png)
![Screenshot 2022-07-05 19 43 40](https://user-images.githubusercontent.com/6265945/177435321-0a8b9ef0-03a1-4e51-a94a-ace1c85ff121.png)
![Screenshot 2022-07-05 19 44 15](https://user-images.githubusercontent.com/6265945/177435324-e5c4f09b-42e4-47f9-8c57-ff6040964700.png)
![Screenshot 2022-07-05 19 44 18](https://user-images.githubusercontent.com/6265945/177435326-c94f6ab6-46ef-41bc-a8f8-828f849699c6.png)
![Screenshot 2022-07-05 19 44 28](https://user-images.githubusercontent.com/6265945/177435327-f4bc9f53-fc01-4926-b879-152c422df35a.png)

**Comment by Gohloum** [comment]
Oops, I forgot this one with the debug info:
![Screenshot 2022-07-05 19 56 16](https://user-images.githubusercontent.com/6265945/177435528-4c67deb5-e5a0-4e46-b911-d86f293a9212.png)

**Comment by aesisify** [comment]
Having the same issue. Anything on this one?

**Comment by dustyroom-studio** [comment]
- In the ['Flat Kit in URP'](https://flatkit.dustyroom.com/#8-flat-kit-in-urp) chapter, we recommend to import Flat Kit into an initially URP project, not an 'upgraded' from Built-In RP' one, in order to use Flat Kit out of the box. Of course, it is ok to use the latter way but Unity didn't make a flawless and easy way to 'upgrade' from Built-In RP to URP: importing Universal RP may not be enough, depending on the URP asset you use, you may also need to import ShaderGraph, as well as other dependencies. For example, here are the Unity dependencies in one of our URP projects, they are listed in the Package Manager:
![unity dependencies](https://user-images.githubusercontent.com/74666746/181017691-1bdfa77c-49e5-4edf-9a4b-ef68e50b5000.png)

- Secondly, please, make sure you installed Flat Kit as recommended in the set-up guide — [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit): there are video instructions as well as a written down step-by-step guide. Particularly, please, pay attention to the step 5, where by pressing a button you automatically set all needed settings in _Graphics_ and _Quality_ settings (**for all of the quality levels!**). In a nutshell, here are the settings needed to be set up in order to display the demo scenes correctly:
![image](https://user-images.githubusercontent.com/4502258/181016345-a50080f0-ff7c-4a6c-9709-783477929583.png)
![image](https://user-images.githubusercontent.com/4502258/181016382-920b5c20-ae0e-4ef0-9546-808af76d80ee.png)

- Sometimes, to make a global effect work, like Outline, you'll need to launch the scene (press Play).

- If nothing works, I'd recommend creating a test URP project, which is URP from the beginning, and importing Flat Kit there, finalizing the set-up according to the [guide](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit). If the issue still occurs, please do the following:
  - Clean the Unity Package Manager cache by deleting the 'Dustyroom' folder . The cache folder can be found here:
Mac OS: ~/Library/Unity/Asset Store-5.x (press Shift+Cmd+G in any Finder Window and paste this path)
Windows: %APPDATA%\Unity\Asset Store-5.x (hidden folder)
Linux: ~/.local/share/unity3d/Asset Store-5.x
  - Reload Unity
  - Open Package Manager
  - Locate Flat Kit, download and import it
  - Locate [Readme] file in Assets/Flat Kit, press 'Configure project for URP' button

Please, let us know if the problem persists.

**Comment by aesisify** [comment]
> * In the ['Flat Kit in URP'](https://flatkit.dustyroom.com/#8-flat-kit-in-urp) chapter, we recommend to import Flat Kit into an initially URP project, not an 'upgraded' from Built-In RP' one, in order to use Flat Kit out of the box. Of course, it is ok to use the latter way but Unity didn't make a flawless and easy way to 'upgrade' from Built-In RP to URP: importing Universal RP may not be enough, depending on the URP asset you use, you may also need to import ShaderGraph, as well as other dependencies. For example, here are the Unity dependencies in one of our URP projects, they are listed in the Package Manager:
>   ![unity dependencies](https://user-images.githubusercontent.com/74666746/181017691-1bdfa77c-49e5-4edf-9a4b-ef68e50b5000.png)
> * Secondly, please, make sure you installed Flat Kit as recommended in the set-up guide — [here](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit): there are video instructions as well as a written down step-by-step guide. Particularly, please, pay attention to the step 5, where by pressing a button you automatically set all needed settings in _Graphics_ and _Quality_ settings (**for all of the quality levels!**). In a nutshell, here are the settings needed to be set up in order to display the demo scenes correctly:
>   ![image](https://user-images.githubusercontent.com/4502258/181016345-a50080f0-ff7c-4a6c-9709-783477929583.png)
>   ![image](https://user-images.githubusercontent.com/4502258/181016382-920b5c20-ae0e-4ef0-9546-808af76d80ee.png)
> * Sometimes, to make a global effect work, like Outline, you'll need to launch the scene (press Play).
> * If nothing works, I'd recommend creating a test URP project, which is URP from the beginning, and importing Flat Kit there, finalizing the set-up according to the [guide](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit). If the issue still occurs, please do the following:
>   
>   * Clean the Unity Package Manager cache by deleting the 'Dustyroom' folder . The cache folder can be found here:
>     Mac OS: ~/Library/Unity/Asset Store-5.x (press Shift+Cmd+G in any Finder Window and paste this path)
>     Windows: %APPDATA%\Unity\Asset Store-5.x (hidden folder)
>     Linux: ~/.local/share/unity3d/Asset Store-5.x
>   * Reload Unity
>   * Open Package Manager
>   * Locate Flat Kit, download and import it
>   * Locate [Readme] file in Assets/Flat Kit, press 'Configure project for URP' button
> 
> Please, let us know if the problem persists.

Thanks for the quick reply! The problem was PlasticSCM which probably screwed some settings when creating a new repo. 

For those having the same issue, Resetting URP settings using the button in the Readme file, right clicking the FlatKit folder and Reimporting fixed the issue.
