### ISSUE TITLE
Unity locking up while importing Terrain Shader

### ISSUE THREAD

**Issue by docky** [Dustyroom/flat-kit-doc#9]
![image](https://user-images.githubusercontent.com/781542/103628677-42f3c680-4f37-11eb-9b7d-3929dc59b729.png)

Unity (2019.4.13f1) has locked up while importing the Terrain Shader.
I had to force quit the editor via Task Manager. 

upon restarting the console gave this error:
"A default asset was created for 'Assets/FlatKit/Shaders/StylizedSurface/Terrain.shader' because the asset importer crashed on it last time.
You can select the asset and use the 'Assets -> Reimport' menu command to try importing it again, or you can replace the asset and it will auto import again."

**Comment by dustyroom-studio** [comment]
Hi,

If you are working with the Built-in Rendering Pipeline version of Flat Kit, some time is required in order to get it imported.
It's advised that you used the Universal Rendering Pipeline, as the URP version of Flat Kit loads virtually immediately in a URP project.

If you plan to go on with Built-in RP, however, please start re-importing the asset and give it from 5 to 30 minutes (the time depends on the computer resources).
